"""The immutable raw archive: the one thing in this project that cannot be rebuilt.

Everything else -- Parquet, forwards, smiles, densities -- is derived and can be
regenerated by rerunning the pipeline. These files cannot. A delayed-quote
endpoint serves the present; 14:30 on a given Tuesday happens once, and if the
capture is lost or corrupted it is gone.

Two consequences run through this module:

**Nothing here mutates a capture's contents.** Compression rewrites the
container, never the bytes inside it, and every conversion is proved to
round-trip before the original is released.

**Corruption must be detectable, not merely unlikely.** `manifests/` holds a
SHA-256 per capture, and `verify` is cheap enough to run on a schedule.
"""

from __future__ import annotations

import gzip
import hashlib
import json
import re
from collections.abc import Iterator
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

CAPTURE_RE = re.compile(
    r"^(?P<ticker>[A-Z_]+)_(?P<stamp>\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}Z)\.json(\.gz)?$"
)

STAMP_FORMAT = "%Y-%m-%dT%H-%M-%SZ"


@dataclass(frozen=True, slots=True)
class Capture:
    """One archived payload, identified without opening it."""

    path: Path
    ticker: str
    captured_at: datetime
    compressed: bool

    @property
    def stem(self) -> str:
        """`_SPX_2026-08-11T20-37-03Z` -- the identity shared with the curated
        layer, so raw and Parquet can be matched by name alone."""
        return f"{self.ticker}_{self.captured_at.strftime(STAMP_FORMAT)}"


def parse_name(path: Path) -> Capture | None:
    """Identify a capture from its filename, or None if it is not one.

    Returning None rather than raising: `data/raw` legitimately accumulates
    other things -- a `.tmp` from an interrupted write, a `.DS_Store` -- and
    those should be ignored, not fatal.
    """
    m = CAPTURE_RE.match(path.name)
    if m is None:
        return None
    return Capture(
        path=path,
        ticker=m["ticker"],
        captured_at=datetime.strptime(m["stamp"], STAMP_FORMAT).replace(tzinfo=UTC),
        compressed=path.name.endswith(".gz"),
    )


def scan(raw_dir: Path) -> list[Capture]:
    """Every capture in the archive, oldest first.

    Sorted by capture time rather than filename so the ordering stays correct if
    the naming convention ever changes.
    """
    if not raw_dir.is_dir():
        return []
    found = (parse_name(p) for p in raw_dir.iterdir() if p.is_file())
    return sorted((c for c in found if c), key=lambda c: (c.captured_at, c.ticker))


def load(path: Path) -> dict[str, Any]:
    """Read a capture, compressed or not.

    Callers must not care which; the archive holds both while the Stage 3
    conversion is in flight, and captures taken before it stay readable forever.
    """
    opener = gzip.open if path.name.endswith(".gz") else open
    with opener(path, "rt") as f:
        return json.load(f)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


# ---------------------------------------------------------------------------
# compression
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class CompressionResult:
    capture: Capture
    before: int
    after: int
    skipped: bool = False

    @property
    def ratio(self) -> float:
        return self.before / self.after if self.after else 0.0


def compress(
    capture: Capture, *, level: int = 6, dry_run: bool = False
) -> CompressionResult:
    """Replace one uncompressed capture with a gzipped one, verifying first.

    The order is the entire point:

        1. compress into a temp file next to the original
        2. read the temp file back and compare it to the original, byte for byte
        3. only then unlink the original

    No capture is ever removed until its replacement has been proved to
    reproduce it exactly. A failure at any step leaves the original untouched
    and the temp file cleaned up, so an interrupted run is resumable rather than
    a half-converted archive.

    Raises:
        OSError: the round-trip did not reproduce the original. The original is
            left in place; investigate before retrying.
    """
    if capture.compressed:
        size = capture.path.stat().st_size
        return CompressionResult(capture, before=size, after=size, skipped=True)

    original = capture.path.read_bytes()
    # with_name, not with_suffix: appending is unambiguous, whereas replacing a
    # suffix depends on how the name happens to be split.
    target = capture.path.with_name(capture.path.name + ".gz")
    if dry_run:
        return CompressionResult(
            capture,
            before=len(original),
            after=len(gzip.compress(original, compresslevel=level, mtime=0)),
        )

    tmp = target.with_name(target.name + ".tmp")
    try:
        # mtime=0 so the same input always yields the same bytes; a re-run must
        # not look like a change.
        tmp.write_bytes(gzip.compress(original, compresslevel=level, mtime=0))

        # Prove it round-trips before anything is destroyed.
        with gzip.open(tmp, "rb") as f:
            restored = f.read()
        if restored != original:
            raise OSError(
                f"round-trip mismatch for {capture.path.name}: "
                f"{len(original)} bytes in, {len(restored)} out. "
                "The original has NOT been removed."
            )

        after = tmp.stat().st_size
        tmp.replace(target)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise

    # Only now, with a verified replacement on disk.
    capture.path.unlink()
    return CompressionResult(capture, before=len(original), after=after)


def compress_archive(
    raw_dir: Path, *, level: int = 6, dry_run: bool = False
) -> list[CompressionResult]:
    """Compress every uncompressed capture, one verified file at a time."""
    return [compress(c, level=level, dry_run=dry_run) for c in scan(raw_dir)]


# ---------------------------------------------------------------------------
# integrity manifest
# ---------------------------------------------------------------------------

MANIFEST_HEADER = """\
# Integrity manifest for the raw capture archive.
#
# A delayed-quote endpoint serves the present. These captures cannot be
# re-fetched; if one is corrupted or lost it is gone permanently.
#
# Verify with:  make verify-archive
"""


def write_manifest(raw_dir: Path, manifest_path: Path) -> int:
    """Write a `shasum -c` compatible manifest over the archive.

    The format is deliberately the standard one rather than something bespoke,
    so it can be checked with `shasum -a 256 -c` by someone who has never seen
    this codebase and has no Python environment.
    """
    captures = scan(raw_dir)
    lines = [MANIFEST_HEADER, f"# {len(captures)} captures\n#\n"]
    lines += [f"{sha256(c.path)}  {c.path.name}\n" for c in captures]
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text("".join(lines))
    return len(captures)


def read_manifest(manifest_path: Path) -> dict[str, str]:
    """Parse a manifest into {filename: digest}."""
    entries: dict[str, str] = {}
    for line in manifest_path.read_text().splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        digest, _, name = line.partition("  ")
        if digest and name:
            entries[name.strip()] = digest.strip()
    return entries


@dataclass(frozen=True, slots=True)
class VerifyReport:
    ok: list[str]
    corrupted: list[str]
    """Present but with the wrong digest. The serious case: silent bit rot."""

    missing: list[str]
    """In the manifest, absent from disk."""

    unlisted: list[str]
    """On disk, absent from the manifest -- usually new captures since the
    manifest was last written, which is expected rather than alarming."""

    @property
    def healthy(self) -> bool:
        return not self.corrupted and not self.missing


def verify(raw_dir: Path, manifest_path: Path) -> VerifyReport:
    """Check every capture against the manifest.

    Distinguishes corrupted from missing from unlisted, because they mean
    different things and only two of them are bad.
    """
    expected = read_manifest(manifest_path)
    on_disk = {c.path.name: c.path for c in scan(raw_dir)}

    ok, corrupted, missing = [], [], []
    for name, digest in sorted(expected.items()):
        path = on_disk.get(name)
        if path is None:
            missing.append(name)
        elif sha256(path) == digest:
            ok.append(name)
        else:
            corrupted.append(name)

    return VerifyReport(
        ok=ok,
        corrupted=corrupted,
        missing=missing,
        unlisted=sorted(set(on_disk) - set(expected)),
    )


def iter_payloads(raw_dir: Path) -> Iterator[tuple[Capture, dict[str, Any]]]:
    """Stream every capture with its decoded payload, oldest first.

    A generator because the full archive is ~400 MB decoded and holding it all
    at once is unnecessary for every use it has.
    """
    for capture in scan(raw_dir):
        yield capture, load(capture.path)
